# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_contenulol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contenulol',
        ),
    ]
